<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9voIRL\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9voIRL/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJ9voIRL.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJ9voIRL\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerJ9voIRL\Eccube_KernelProdContainer([
    'container.build_hash' => 'J9voIRL',
    'container.build_id' => '8a078be9',
    'container.build_time' => 1774403371,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9voIRL');
