<?php

namespace Plugin\ContactManagement42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ContactManagement42\Entity\ContactReply;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactReplyRepository extends AbstractRepository
{
    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(
        ManagerRegistry $registry
    ) {
        parent::__construct($registry, ContactReply::class);
    }

}
