<?php

namespace Plugin\ContactManagement42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ContactManagement42\Entity\Config;
use Plugin\ContactManagement42\Entity\ContactStatus;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ContactStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactStatusRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ContactStatus::class);
    }

}
