<?php

/*
 * This file is part of ProductDisplayRank42
 *
 * Copyright(c) U-Mebius Inc. All Rights Reserved.
 *
 * https://umebius.com/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ProductDisplayRank42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ProductDisplayRank42\Entity\Config;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return Config|null
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
